import { MigrationInterface, QueryRunner } from "typeorm";

export class SyncCurrentEntities1778621768379 implements MigrationInterface {
    name = 'SyncCurrentEntities1778621768379'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "incident" DROP CONSTRAINT "FK_incident_reservation"`);
        await queryRunner.query(`ALTER TABLE "incident" DROP CONSTRAINT "FK_incident_previous_reservation"`);
        await queryRunner.query(`ALTER TABLE "incident" DROP CONSTRAINT "FK_incident_space"`);
        await queryRunner.query(`ALTER TABLE "incident" DROP CONSTRAINT "FK_incident_reported_by"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_reservation_user"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_reservation_space"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_reservation_reassigned_space"`);
        await queryRunner.query(`CREATE TABLE "site" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "site_id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_9669a09fcc0eb6d2794a658f647" UNIQUE ("name"), CONSTRAINT "PK_5a3b28c4439c0972c59a0504e6b" PRIMARY KEY ("site_id"))`);
        await queryRunner.query(`CREATE TABLE "building" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "building_id" SERIAL NOT NULL, "name" character varying NOT NULL, "site_id" integer NOT NULL, CONSTRAINT "PK_03b4a92f4aaa6114958969b6a9c" PRIMARY KEY ("building_id"))`);
        await queryRunner.query(`CREATE TABLE "floor" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "floor_id" SERIAL NOT NULL, "name" character varying NOT NULL, "building_id" integer NOT NULL, CONSTRAINT "PK_45e4850aab53c1130ba72995e74" PRIMARY KEY ("floor_id"))`);
        await queryRunner.query(`CREATE TABLE "space_type" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "space_type_id" SERIAL NOT NULL, "name" character varying NOT NULL, CONSTRAINT "UQ_9db739b348060230262f3d7fb58" UNIQUE ("name"), CONSTRAINT "PK_37aa7e1bc3d08a94eceb391c780" PRIMARY KEY ("space_type_id"))`);
        await queryRunner.query(`CREATE TABLE "release" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "release_id" SERIAL NOT NULL, "reason" character varying NOT NULL, "release_time" TIMESTAMP NOT NULL, "reservation_id" integer NOT NULL, CONSTRAINT "UQ_c21d69c76046e6755cc5807d4cb" UNIQUE ("reservation_id"), CONSTRAINT "REL_c21d69c76046e6755cc5807d4c" UNIQUE ("reservation_id"), CONSTRAINT "PK_d3bbe01c30ee7c10ad7037d41a5" PRIMARY KEY ("release_id"))`);
        await queryRunner.query(`CREATE TABLE "check_event" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "check_event_id" SERIAL NOT NULL, "event_type" character varying NOT NULL, "method" character varying NOT NULL, "event_time" TIMESTAMP NOT NULL, "reservation_id" integer NOT NULL, CONSTRAINT "PK_d60d95528cf5fcf3c50f8182caa" PRIMARY KEY ("check_event_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."visit_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`CREATE TABLE "visit" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "visit_id" SERIAL NOT NULL, "visitor_name" character varying NOT NULL, "company" character varying NOT NULL, "visit_date" TIMESTAMP NOT NULL DEFAULT now(), "status" "public"."visit_status_enum" NOT NULL DEFAULT 'pending', "priority_level_id" integer NOT NULL, "user_id" integer NOT NULL, CONSTRAINT "PK_95812f2b19e2ffbf8ad42a15c07" PRIMARY KEY ("visit_id"))`);
        await queryRunner.query(`CREATE TABLE "priority_level" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "priority_level_id" SERIAL NOT NULL, "name" character varying NOT NULL, "scale" character varying NOT NULL, CONSTRAINT "PK_3d08a558018ed5a4c636025976d" PRIMARY KEY ("priority_level_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_need_status_enum" AS ENUM('active', 'inactive', 'expired')`);
        await queryRunner.query(`CREATE TABLE "user_need" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "user_need_id" SERIAL NOT NULL, "need_type" character varying NOT NULL, "start_date" TIMESTAMP NOT NULL, "end_date" TIMESTAMP NOT NULL, "status" "public"."user_need_status_enum" NOT NULL DEFAULT 'active', "reason" character varying NOT NULL, "user_id" integer NOT NULL, "priority_level_id" integer NOT NULL, CONSTRAINT "PK_402d2d7ea52e7de6fc8c4f01286" PRIMARY KEY ("user_need_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."event_status_enum" AS ENUM('planned', 'ongoing', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "event" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "event_id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text, "location" character varying, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "expected_attendees" integer, "status" "public"."event_status_enum" NOT NULL DEFAULT 'planned', "user_need_id" integer NOT NULL, "created_by" integer NOT NULL, CONSTRAINT "PK_fe0840e4557d98ed53b0ae51466" PRIMARY KEY ("event_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."points_ledger_operation_type_enum" AS ENUM('add', 'subtract')`);
        await queryRunner.query(`CREATE TABLE "points_ledger" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "points_id" SERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "reason" character varying NOT NULL, "points_delta" integer NOT NULL, "operation_type" "public"."points_ledger_operation_type_enum" NOT NULL DEFAULT 'add', "balance" integer NOT NULL, "reference_type" character varying NOT NULL, "reference_id" character varying, "user_id" integer NOT NULL, CONSTRAINT "PK_acd1999e9626d1f0cfa9a0d6d0c" PRIMARY KEY ("points_id"))`);
        await queryRunner.query(`CREATE TABLE "badge" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "badge_id" SERIAL NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL, "icon" character varying NOT NULL, "description" text, "criteria" character varying NOT NULL, "points_reward" integer, "is_active" boolean NOT NULL DEFAULT true, "unlock_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_c77f5118dd4ede320359aa4018a" PRIMARY KEY ("badge_id"))`);
        await queryRunner.query(`CREATE TABLE "user_badge" ("user_id" integer NOT NULL, "badge_id" integer NOT NULL, "unlocked_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1e9b8cbf71c28a587a3f09e366a" PRIMARY KEY ("user_id", "badge_id"))`);
        await queryRunner.query(`CREATE TABLE "vehicle" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "vehicle_id" SERIAL NOT NULL, "plate_number" character varying NOT NULL, "brand" character varying NOT NULL, "model" character varying NOT NULL, "color" character varying, "year" integer, "seats_total" integer NOT NULL, "is_active" boolean NOT NULL DEFAULT true, "owner_id" integer NOT NULL, CONSTRAINT "UQ_b9040932fbdee7361d64e6f15a2" UNIQUE ("plate_number"), CONSTRAINT "PK_8b107f0822abfa70997e54a0a61" PRIMARY KEY ("vehicle_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."trip_rider_status_enum" AS ENUM('requested', 'accepted', 'rejected', 'cancelled', 'boarded', 'no_show', 'completed')`);
        await queryRunner.query(`CREATE TABLE "trip_rider" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "trip_id" integer NOT NULL, "user_id" integer NOT NULL, "status" "public"."trip_rider_status_enum" NOT NULL DEFAULT 'accepted', "requested_at" TIMESTAMP NOT NULL DEFAULT now(), "responded_at" TIMESTAMP, "joined_at" TIMESTAMP, "left_at" TIMESTAMP, CONSTRAINT "PK_7c9ca3dfd937eac53cd5a091bb8" PRIMARY KEY ("trip_id", "user_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."carpool_trip_status_enum" AS ENUM('draft', 'open', 'full', 'in_progress', 'completed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "carpool_trip" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "trip_id" SERIAL NOT NULL, "trip_date" TIMESTAMP NOT NULL, "status" "public"."carpool_trip_status_enum" NOT NULL DEFAULT 'open', "seats_available" integer NOT NULL, "seats_total" integer NOT NULL, "origin" character varying NOT NULL, "destination" character varying NOT NULL, "notes" text, "driver_id" integer NOT NULL, "vehicle_id" integer NOT NULL, CONSTRAINT "PK_160a526e5abfa7135d5d137ecd6" PRIMARY KEY ("trip_id"))`);
        await queryRunner.query(`CREATE TABLE "space_user_usage" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "user_id" integer NOT NULL, "space_id" integer NOT NULL, CONSTRAINT "PK_b18f242c40b71baf106bfc77576" PRIMARY KEY ("user_id", "space_id"))`);
        await queryRunner.query(`CREATE TABLE "zone" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "zone_id" SERIAL NOT NULL, "name" character varying NOT NULL, "floor_id" integer NOT NULL, CONSTRAINT "PK_b87da63fe57855a705d64478e25" PRIMARY KEY ("zone_id"))`);
        await queryRunner.query(`CREATE TABLE "block" ("createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, "block_id" SERIAL NOT NULL, "reason" character varying NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP, "space_id" integer, "zone_id" integer, CONSTRAINT "PK_f15e3d5df038c5c749cd12b77e3" PRIMARY KEY ("block_id"))`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "location"`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "UQ_59cde757d34ded6635d50fbb8e9" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD "event_id" integer`);
        await queryRunner.query(`ALTER TABLE "space" ADD "code" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ADD CONSTRAINT "UQ_64e2ade5237f834bd53d798e56b" UNIQUE ("code")`);
        await queryRunner.query(`ALTER TABLE "space" ADD "is_accessible" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "space" ADD "is_priority" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "space" ADD "zone_id" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" ADD "space_type_id" integer`);
        await queryRunner.query(`ALTER TABLE "reservation" ALTER COLUMN "user_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservation" ALTER COLUMN "space_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "status"`);
        await queryRunner.query(`CREATE TYPE "public"."space_status_enum" AS ENUM('available', 'occupied', 'maintenance', 'blocked')`);
        await queryRunner.query(`ALTER TABLE "space" ADD "status" "public"."space_status_enum" NOT NULL DEFAULT 'available'`);
        await queryRunner.query(`ALTER TABLE "building" ADD CONSTRAINT "FK_f912f7e8b57b7999e8d4ae0588f" FOREIGN KEY ("site_id") REFERENCES "site"("site_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "floor" ADD CONSTRAINT "FK_1565850c51d1cc30e896101fa77" FOREIGN KEY ("building_id") REFERENCES "building"("building_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release" ADD CONSTRAINT "FK_c21d69c76046e6755cc5807d4cb" FOREIGN KEY ("reservation_id") REFERENCES "reservation"("reservation_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "check_event" ADD CONSTRAINT "FK_8e38ae60178428e9e9117cecab3" FOREIGN KEY ("reservation_id") REFERENCES "reservation"("reservation_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visit" ADD CONSTRAINT "FK_4fe99f2addb42d74e806ff43b4e" FOREIGN KEY ("priority_level_id") REFERENCES "priority_level"("priority_level_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "visit" ADD CONSTRAINT "FK_359bbdf2205ac56732464652f99" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_need" ADD CONSTRAINT "FK_c4c66ff412b116c9fb0faca8cb6" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_need" ADD CONSTRAINT "FK_025bc5aad9d85372040428c607f" FOREIGN KEY ("priority_level_id") REFERENCES "priority_level"("priority_level_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_62b07bc7a416bf98abfba27047b" FOREIGN KEY ("user_need_id") REFERENCES "user_need"("user_need_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event" ADD CONSTRAINT "FK_f14a467e5564751af8153ac3167" FOREIGN KEY ("created_by") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incident" ADD CONSTRAINT "FK_8ffb78da8fc63aa847635614ec0" FOREIGN KEY ("reservation_id") REFERENCES "reservation"("reservation_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incident" ADD CONSTRAINT "FK_23ab18128bb0939d3e768faf414" FOREIGN KEY ("previous_reservation_id") REFERENCES "reservation"("reservation_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incident" ADD CONSTRAINT "FK_121cde91e806ae580a43f4b90b0" FOREIGN KEY ("space_id") REFERENCES "space"("space_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incident" ADD CONSTRAINT "FK_583453357cb3e8da99d4bc5a28c" FOREIGN KEY ("reported_by") REFERENCES "user"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_e219b0a4ff01b85072bfadf3fd7" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_ebd0b3df8e405475840b64343e0" FOREIGN KEY ("space_id") REFERENCES "space"("space_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_e727e788ddaa51681f0d495c6d9" FOREIGN KEY ("event_id") REFERENCES "event"("event_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_e62e445b5606e787fb9a8c4a765" FOREIGN KEY ("reassigned_space_id") REFERENCES "space"("space_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "points_ledger" ADD CONSTRAINT "FK_da695f16d02317721eb76711fec" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badge" ADD CONSTRAINT "FK_d988bb483f614b0541c6de7b3ce" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_badge" ADD CONSTRAINT "FK_b0992699126a527b53d0b8d9d86" FOREIGN KEY ("badge_id") REFERENCES "badge"("badge_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "vehicle" ADD CONSTRAINT "FK_ac9360a2c16ec48e49e08e40d2c" FOREIGN KEY ("owner_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_rider" ADD CONSTRAINT "FK_6eecc324e5ecb9e417865bc1b13" FOREIGN KEY ("trip_id") REFERENCES "carpool_trip"("trip_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trip_rider" ADD CONSTRAINT "FK_f7dc8295a22db96723711670b3f" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carpool_trip" ADD CONSTRAINT "FK_23509b9ad39fd50767b50dda3d0" FOREIGN KEY ("driver_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carpool_trip" ADD CONSTRAINT "FK_f7ab5e33edfa1cbdb1b2f671769" FOREIGN KEY ("vehicle_id") REFERENCES "vehicle"("vehicle_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space_user_usage" ADD CONSTRAINT "FK_06e64b559859d842d4d47a14d66" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space_user_usage" ADD CONSTRAINT "FK_423e1bb253d9c923d9a7f2521bc" FOREIGN KEY ("space_id") REFERENCES "space"("space_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space" ADD CONSTRAINT "FK_3f182a339d6741a512153a19253" FOREIGN KEY ("space_type_id") REFERENCES "space_type"("space_type_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "space" ADD CONSTRAINT "FK_55a07212e92ebb338e982771aca" FOREIGN KEY ("zone_id") REFERENCES "zone"("zone_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "zone" ADD CONSTRAINT "FK_a62b650f24e35df37a259f91923" FOREIGN KEY ("floor_id") REFERENCES "floor"("floor_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "block" ADD CONSTRAINT "FK_f5f38bb941c9afd9407e4330510" FOREIGN KEY ("space_id") REFERENCES "space"("space_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "block" ADD CONSTRAINT "FK_881938434a5225617e72c0943ea" FOREIGN KEY ("zone_id") REFERENCES "zone"("zone_id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "block" DROP CONSTRAINT "FK_881938434a5225617e72c0943ea"`);
        await queryRunner.query(`ALTER TABLE "block" DROP CONSTRAINT "FK_f5f38bb941c9afd9407e4330510"`);
        await queryRunner.query(`ALTER TABLE "zone" DROP CONSTRAINT "FK_a62b650f24e35df37a259f91923"`);
        await queryRunner.query(`ALTER TABLE "space" DROP CONSTRAINT "FK_55a07212e92ebb338e982771aca"`);
        await queryRunner.query(`ALTER TABLE "space" DROP CONSTRAINT "FK_3f182a339d6741a512153a19253"`);
        await queryRunner.query(`ALTER TABLE "space_user_usage" DROP CONSTRAINT "FK_423e1bb253d9c923d9a7f2521bc"`);
        await queryRunner.query(`ALTER TABLE "space_user_usage" DROP CONSTRAINT "FK_06e64b559859d842d4d47a14d66"`);
        await queryRunner.query(`ALTER TABLE "carpool_trip" DROP CONSTRAINT "FK_f7ab5e33edfa1cbdb1b2f671769"`);
        await queryRunner.query(`ALTER TABLE "carpool_trip" DROP CONSTRAINT "FK_23509b9ad39fd50767b50dda3d0"`);
        await queryRunner.query(`ALTER TABLE "trip_rider" DROP CONSTRAINT "FK_f7dc8295a22db96723711670b3f"`);
        await queryRunner.query(`ALTER TABLE "trip_rider" DROP CONSTRAINT "FK_6eecc324e5ecb9e417865bc1b13"`);
        await queryRunner.query(`ALTER TABLE "vehicle" DROP CONSTRAINT "FK_ac9360a2c16ec48e49e08e40d2c"`);
        await queryRunner.query(`ALTER TABLE "user_badge" DROP CONSTRAINT "FK_b0992699126a527b53d0b8d9d86"`);
        await queryRunner.query(`ALTER TABLE "user_badge" DROP CONSTRAINT "FK_d988bb483f614b0541c6de7b3ce"`);
        await queryRunner.query(`ALTER TABLE "points_ledger" DROP CONSTRAINT "FK_da695f16d02317721eb76711fec"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_e62e445b5606e787fb9a8c4a765"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_e727e788ddaa51681f0d495c6d9"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_ebd0b3df8e405475840b64343e0"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "FK_e219b0a4ff01b85072bfadf3fd7"`);
        await queryRunner.query(`ALTER TABLE "incident" DROP CONSTRAINT "FK_583453357cb3e8da99d4bc5a28c"`);
        await queryRunner.query(`ALTER TABLE "incident" DROP CONSTRAINT "FK_121cde91e806ae580a43f4b90b0"`);
        await queryRunner.query(`ALTER TABLE "incident" DROP CONSTRAINT "FK_23ab18128bb0939d3e768faf414"`);
        await queryRunner.query(`ALTER TABLE "incident" DROP CONSTRAINT "FK_8ffb78da8fc63aa847635614ec0"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_f14a467e5564751af8153ac3167"`);
        await queryRunner.query(`ALTER TABLE "event" DROP CONSTRAINT "FK_62b07bc7a416bf98abfba27047b"`);
        await queryRunner.query(`ALTER TABLE "user_need" DROP CONSTRAINT "FK_025bc5aad9d85372040428c607f"`);
        await queryRunner.query(`ALTER TABLE "user_need" DROP CONSTRAINT "FK_c4c66ff412b116c9fb0faca8cb6"`);
        await queryRunner.query(`ALTER TABLE "visit" DROP CONSTRAINT "FK_359bbdf2205ac56732464652f99"`);
        await queryRunner.query(`ALTER TABLE "visit" DROP CONSTRAINT "FK_4fe99f2addb42d74e806ff43b4e"`);
        await queryRunner.query(`ALTER TABLE "check_event" DROP CONSTRAINT "FK_8e38ae60178428e9e9117cecab3"`);
        await queryRunner.query(`ALTER TABLE "release" DROP CONSTRAINT "FK_c21d69c76046e6755cc5807d4cb"`);
        await queryRunner.query(`ALTER TABLE "floor" DROP CONSTRAINT "FK_1565850c51d1cc30e896101fa77"`);
        await queryRunner.query(`ALTER TABLE "building" DROP CONSTRAINT "FK_f912f7e8b57b7999e8d4ae0588f"`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."space_status_enum"`);
        await queryRunner.query(`ALTER TABLE "space" ADD "status" character varying NOT NULL DEFAULT 'available'`);
        await queryRunner.query(`ALTER TABLE "reservation" ALTER COLUMN "space_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reservation" ALTER COLUMN "user_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "space_type_id"`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "zone_id"`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "is_priority"`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "is_accessible"`);
        await queryRunner.query(`ALTER TABLE "space" DROP CONSTRAINT "UQ_64e2ade5237f834bd53d798e56b"`);
        await queryRunner.query(`ALTER TABLE "space" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP COLUMN "event_id"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP CONSTRAINT "UQ_59cde757d34ded6635d50fbb8e9"`);
        await queryRunner.query(`ALTER TABLE "reservation" DROP COLUMN "code"`);
        await queryRunner.query(`ALTER TABLE "space" ADD "location" character varying`);
        await queryRunner.query(`ALTER TABLE "space" ADD "type" character varying NOT NULL DEFAULT 'desk'`);
        await queryRunner.query(`ALTER TABLE "space" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`DROP TABLE "block"`);
        await queryRunner.query(`DROP TABLE "zone"`);
        await queryRunner.query(`DROP TABLE "space_user_usage"`);
        await queryRunner.query(`DROP TABLE "carpool_trip"`);
        await queryRunner.query(`DROP TYPE "public"."carpool_trip_status_enum"`);
        await queryRunner.query(`DROP TABLE "trip_rider"`);
        await queryRunner.query(`DROP TYPE "public"."trip_rider_status_enum"`);
        await queryRunner.query(`DROP TABLE "vehicle"`);
        await queryRunner.query(`DROP TABLE "user_badge"`);
        await queryRunner.query(`DROP TABLE "badge"`);
        await queryRunner.query(`DROP TABLE "points_ledger"`);
        await queryRunner.query(`DROP TYPE "public"."points_ledger_operation_type_enum"`);
        await queryRunner.query(`DROP TABLE "event"`);
        await queryRunner.query(`DROP TYPE "public"."event_status_enum"`);
        await queryRunner.query(`DROP TABLE "user_need"`);
        await queryRunner.query(`DROP TYPE "public"."user_need_status_enum"`);
        await queryRunner.query(`DROP TABLE "priority_level"`);
        await queryRunner.query(`DROP TABLE "visit"`);
        await queryRunner.query(`DROP TYPE "public"."visit_status_enum"`);
        await queryRunner.query(`DROP TABLE "check_event"`);
        await queryRunner.query(`DROP TABLE "release"`);
        await queryRunner.query(`DROP TABLE "space_type"`);
        await queryRunner.query(`DROP TABLE "floor"`);
        await queryRunner.query(`DROP TABLE "building"`);
        await queryRunner.query(`DROP TABLE "site"`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_reservation_reassigned_space" FOREIGN KEY ("reassigned_space_id") REFERENCES "space"("space_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_reservation_space" FOREIGN KEY ("space_id") REFERENCES "space"("space_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reservation" ADD CONSTRAINT "FK_reservation_user" FOREIGN KEY ("user_id") REFERENCES "user"("user_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incident" ADD CONSTRAINT "FK_incident_reported_by" FOREIGN KEY ("reported_by") REFERENCES "user"("user_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incident" ADD CONSTRAINT "FK_incident_space" FOREIGN KEY ("space_id") REFERENCES "space"("space_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incident" ADD CONSTRAINT "FK_incident_previous_reservation" FOREIGN KEY ("previous_reservation_id") REFERENCES "reservation"("reservation_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "incident" ADD CONSTRAINT "FK_incident_reservation" FOREIGN KEY ("reservation_id") REFERENCES "reservation"("reservation_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
